### ISSUE TITLE
change tab trigger re-rendering

### ISSUE THREAD

**Issue by adrianha** [davidtheclark/react-aria-tabpanel#12]
Hello David,
Im facing an issue when i'm navigating into another tab, image on the next tab will be re-rendering. its happening everytime i moved into that tab...
Any idea? @davidtheclark

**Comment by davidtheclark** [comment]
> image on the next tab will be re-rendering

The panels do mount and unmount as they are selected. But I don't understand what that's a problem for you?

**Comment by adrianha** [comment]
Images on selected tab will be flickering every time i select the tab.. Image size is only 4KB.. But if i use fontawesome, everthing is good

**Comment by davidtheclark** [comment]
That's probably because the panels are mounting and unmounting. I wonder what would happen if instead they had `display: none` toggled on and off. Open to a PR!

**Comment by adrianha** [comment]
I've sent you this pull request #13 .
Tell me what do u think?

**Comment by adrianha** [comment]
have you seen the PR @davidtheclark ?

**Comment by davidtheclark** [comment]
I've been backpacking, so haven't been online for a week. I will try to look into this soon.

**Comment by davidtheclark** [comment]
Closed by #13.
