### ISSUE TITLE
Support for dynamic tabs?

### ISSUE THREAD

**Issue by sgilligan** [davidtheclark/react-aria-tabpanel#16]
Hi @davidtheclark, does this support dynamically modifying tabs? I'm running into unpredictable behaviour and I'm not sure if because of how I'm doing this (I have a use-case where the number of tabs can vary dynamically).

I've created a test showing my problem based on the stateless example here: https://esnextb.in/?gist=9e389ce9ef672543348eb7fa4d0a774b

Without reducing the tab count, the arrow keys work as expected. If you then reduce the tab count, the arrow nav works one direction, but not the other. If you then restore the tab count, and then reduce once again, the arrow navigation stops working completely (tested Chrome, Windows and OSX)

**Comment by davidtheclark** [comment]
@sgilligan The module does not currently support this, because of the way arrow keys are managed. There's a list of elements that arrows cycle through, a [focus-group](https://github.com/davidtheclark/focus-group); and that list would need to be updated when you remove & add new tabs.

**Comment by sgilligan** [comment]
ok .. thanks for the prompt reply.

**Comment by davidtheclark** [comment]
@sgilligan If you can think of a good API for this, you're welcome to open a PR!
