### ISSUE TITLE
AriaTabPanel-Tab: React.createClass is deprecated and will be removed in version 16.

### ISSUE THREAD

**Issue by riccardogenova** [davidtheclark/react-aria-tabpanel#18]
Warning: AriaTabPanel-Tab: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by davidtheclark** [comment]
@riccardogenova I'd love a PR updating the syntax. I'm not using this library much myself right now so don't feel the urgency: anybody who'd like to upgrade soon can make this happen!
