### ISSUE TITLE
Suggesting to remove the divs inside the <li>

### ISSUE THREAD

**Issue by eguyot** [davidtheclark/react-aria-tabpanel#21]
Hello this is a suggestion. 
Why is there 2 `div`s inside of each `li` ? 
Couldn't it be cleaner ? Maybe we could apply the active class to the `li` directly ?
Do you think this could be possible to achieve in some way ?

**Comment by davidtheclark** [comment]
I'm not worried about the `<div>`s: I don't know of any negative effect they have. Do you?

I'm open to a PR allowing different elements, though!

**Comment by eguyot** [comment]
Well I found it a bit heavy in html terms. We have 2 imbricated DIVs into one li. 
But we manage to have only one div instead of 2 by modifying the code in the demo we used. 
I'm more concerned now about this enzyme limitation... for now I don't really know how to do this...

**Comment by davidtheclark** [comment]
> I'm more concerned now about this enzyme limitation... for now I don't really know how to do this...

@eguyot: How about `.find`ing the `<div>` that and calling its `onClick` prop, e.g. `wrapper.find('div-selector').prop('onClick')()`?

**Comment by eguyot** [comment]
Maybe... frankly, I used another lib ^^'
