### ISSUE TITLE
Unable to Change to First Tab When Dynamically Adding Tabs

### ISSUE THREAD

**Issue by danielyearwood** [davidtheclark/react-aria-tabpanel#23]
Let's say I've started my tabs with just one tab. A user of my app triggers some action that adds another tab on the fly and sets the new tab to active. When I try to click the first tab the onChange event never fires and I'm unable to view the first tab. If I click the newly created tab first and then click the first tab, it then fires the onChange event and switches to the first tab. This happens even after I've created multiple tabs. Does this package support adding/removing tabs dynamically as I've described?

Thanks for all the awesomeness you've created here.

**Comment by davidtheclark** [comment]
Thanks @danielyearwood. If it doesn't work (have you tried it?), I'm open to a PR adding that functionality.

**Comment by danielyearwood** [comment]
@davidtheclark Yeah I've tried it. I'm actually seeing this when I implement it with one tab and then dynamically adding others. I get the functionality back by clicking on the new tab, then clicking back on the first. I'm using it to open and close UI elements in a designated area of an app and discovered when I implemented it. I would love to help out if possible.

**Comment by danielyearwood** [comment]
@davidtheclark I submitted a PR for this. It's my first one, so let me know if I did anything wrong lol. Thanks for letting me contribute. 

BTW, I also noticed that when controlling the active tab via parent state, if you change the active tab via state without the user clicking a tab, they cannot click the previously focused tab. I added a fix for this as well and documented in my notes.

**Comment by nring** [comment]
Thanks for submitting this PR @danielyearwood! We just ran into your secondary bug when trying to programmatically change tabs from an external button.

**Comment by sah267** [comment]
@danielyearwood just ran into the focus bug as well! Thanks for submitting a fix!

**Comment by davidtheclark** [comment]
Closed by #25.
