### ISSUE TITLE
Error: Cannot find module './dist-modules/ariaTabPanel.js'

### ISSUE THREAD

**Issue by limulus** [davidtheclark/react-aria-tabpanel#3]
Hey David, it just so happens I’m finally giving React a try, and I needed some tabs, and so I thought “I wonder if David Clark has an accessible tab panel module.” And, well sure enough…  😄

Anyway, I get this error when importing `react-aria-tabpanel`: `Error: Cannot find module './dist-modules/ariaTabPanel.js'`. When I change the module being required in `index.js` to be `./dist/AriaTabPanel.js` it seems to fix it, so I’m guessing it is probably just a case of forgetting to not update index.js to point at the correct file.

**Comment by davidtheclark** [comment]
Yes. I updated all these accessible modules for React 14 at high speeds yesterday and must have screwed that up. I'll try to get a fix pushed real soon. Thanks a lot for pointing it out!

**Comment by davidtheclark** [comment]
@limulus : Fix should be released as 3.0.1. (Boy, I hope I didn't screw it up again ... I've been rushing a little too much with this module.) Let me know if it works, if you have feedback about the module, etc. Thanks!

**Comment by limulus** [comment]
Yep, v3.0.1 did the trick! Thanks much! I will indeed let you know if I have any feedback.
