### ISSUE TITLE
Two little things

### ISSUE THREAD

**Issue by StommePoes** [davidtheclark/react-aria-tabpanel#4]
Maybe three.
1. I luv me some lang attrs on the &lt;html&gt; element (I actually don't even see one so the browser would just make one). This for less SR language heuristics and other benefits. http://adrianroselli.com/2015/01/on-use-of-lang-attribute.html
2. Dunno how useful it is, but because aria-controls isn't presently doing much in SRs, people have been adding aria-describedby on panels pointing to the tabs.
3. Panel id's are numbers, HTML says id's can't start with a digit. p1, p2... would work.
er, 4:
aria-selected role on the current/active tab.

**Comment by davidtheclark** [comment]
@StommePoes: Thanks so much for the ideas!

> people have been adding aria-describedby on panels pointing to the tabs.

This is one of the main reasons I open-sourced the components: in hopes to garner some insider knowledge from other people. I'd be happy to change the aria attributes to use `aria-describedby`. Do you have any links that I could read to learn about effective tab implementations that use this, or is it just knowledge that you've picked up?

> Panel id's are numbers, HTML says id's can't start with a digit

Right on. I'll fix it soon.

> aria-selected role on the current/active tab.

Same with this. Will fix soon.

> I luv me some lang attrs on the <html> element

I don't understand this suggestion. Is this just a suggestion for improving the demo page, or is there something you'd expect the component to do that it doesn't do?

**Comment by StommePoes** [comment]
&lt;html lang="en"&gt;

For a few reasons:
1. everyone ought to do it. If we only cared about screen readers, take the example of me having mine set to Dutch as default. If I come to an English page, without the lang attr I may have to go into my settings and switch it manually. With the lang attr, I get this for free. 
Adrian's article kinda adds some more extra's.

This is not specific to your demo/example, this is something I've started telling everyone. Like a deranged a11y-Jahova's Witness :P
2. For the reason above, I've started advocating the lang attr on all code examples, because hey, I learned coding partially by copy-paste, and so do most other people. So it's good to have the good-example in sample (and demo) code. Since the page happens to be English, I'd just do "en".

Re the describedby: I myself also keep the aria-controls, because some day I guess it'll do something :P but last time I read on it, nobody was actually doing anything useful. So a few people have started adding aria-describedby (not in place of controls, but with it) and often making the panel itself (or the first heading) focusable and then it can help the association. So stuff I've read others do + tried myself.

As a keyboarder, I've been avoiding the recommendation for the up/down arrows, simply because I use those to scroll the page down, when the panels are longer than my screen. But one way to keep the recommendations as well as let me scroll is to let the panel itself be focusable (what my next Tab would bring me to from the tabs) and now my arrows are free for scrolling without having been jumped past the whole tab-panel widget. (I added an issue to wherever the github tracker is for tab panels, the spec is on github!).

**Comment by davidtheclark** [comment]
- Html lang attr is now up on the example.
- `aria-selected` attr is added to tabs and released in 3.0.3.
- I made a new issue for aria-describedbby, since that will entail a breaking release: https://github.com/davidtheclark/react-aria-tabpanel/issues/5
- I will follow that issue you filed and see how it goes. In the meantime, with the next major release I might add focus to the panels, which would help out with the arrow-scrolling issue you describe.

Thanks again.

**Comment by StommePoes** [comment]
Very cool. I'm so glad you made these demos, I'm struggling with React and it's always great to see something with more complexity than a tutorial out there.
